version: 2.1

orbs:
  node: circleci/node@5.1.0
  slack: circleci/slack@4.10.1

jobs:
  build-and-test-job:
    docker:
      - image: cypress/base:18.16.0
    working_directory: ~/repo  
    environment:
      NODE_ENV: "circleci"
    resource_class: large 
    steps:
      - checkout
      - run:
          name: Install Node.js packages
          command: npm install
      - run:
          name: Run tests
          command: npx cypress run

  scheduled-job:
    docker:
      - image: cypress/base:18.16.0
    environment:
      NODE_ENV: "circleci"
    resource_class: large    
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npx cypress run

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-and-test-job
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - main

  each-test-push:
    jobs:
      - scheduled-job
  # each-test-push:
  #   jobs:
  #     - build-and-test-job

